//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferenceService.WebApi.PrintServerBridgeWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.server.ru/PrintServerBridgeWS/", ConfigurationName="PrintServerBridgeWS.PrintServerBridgeWS")]
    public interface PrintServerBridgeWS {
        
        // CODEGEN: Generating message contract since the wrapper name (storeRequest) of message storeRequest does not match the default value (store)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.server.ru/PrintServerBridgeWS/store", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GID))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(headerType))]
        ReferenceService.WebApi.PrintServerBridgeWS.storeResponse store(ReferenceService.WebApi.PrintServerBridgeWS.storeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.server.ru/PrintServerBridgeWS/store", ReplyAction="*")]
        System.Threading.Tasks.Task<ReferenceService.WebApi.PrintServerBridgeWS.storeResponse> storeAsync(ReferenceService.WebApi.PrintServerBridgeWS.storeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.server.ru/PrintServerBridgeWS/")]
    public partial class ReportProperties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string reportCodeField;
        
        private int numberOfCopiesField;
        
        private ReportEntry[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string reportCode {
            get {
                return this.reportCodeField;
            }
            set {
                this.reportCodeField = value;
                this.RaisePropertyChanged("reportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numberOfCopies {
            get {
                return this.numberOfCopiesField;
            }
            set {
                this.numberOfCopiesField = value;
                this.RaisePropertyChanged("numberOfCopies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ReportEntry[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.server.ru/PrintServerBridgeWS/")]
    public partial class ReportEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/types")]
    public partial class GID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private systemCodeEnum systemCodeField;
        
        private string branchField;
        
        private TypeObjectEnum typeObjectField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public systemCodeEnum systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TypeObjectEnum typeObject {
            get {
                return this.typeObjectField;
            }
            set {
                this.typeObjectField = value;
                this.RaisePropertyChanged("typeObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/types")]
    public enum systemCodeEnum {
        sys1,
        sys2,
        sys3
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/types")]
    public enum TypeObjectEnum {
        /// <remarks/>
        INTERBANK,
        /// <remarks/>
        DEBITCARD,
        /// <remarks/>
        CREDITCARD
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/types")]
    public partial class headerType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private systemCodeEnum systemCodeField;
        
        private string userIdField;
        
        private string userPasswordField;
        
        private string transactionIdField;
        
        private string parentTransactionIdField;
        
        private string componentIdField;
        
        private string parentComponentIdField;
        
        private string replyToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public systemCodeEnum systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string userPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
                this.RaisePropertyChanged("userPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string parentTransactionId {
            get {
                return this.parentTransactionIdField;
            }
            set {
                this.parentTransactionIdField = value;
                this.RaisePropertyChanged("parentTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string componentId {
            get {
                return this.componentIdField;
            }
            set {
                this.componentIdField = value;
                this.RaisePropertyChanged("componentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string parentComponentId {
            get {
                return this.parentComponentIdField;
            }
            set {
                this.parentComponentIdField = value;
                this.RaisePropertyChanged("parentComponentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string replyTo {
            get {
                return this.replyToField;
            }
            set {
                this.replyToField = value;
                this.RaisePropertyChanged("replyTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/result")]
    public partial class serviceResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private systemCodeEnum systemCodeField;
        
        private resultTypeEnum resultTypeField;
        
        private string resultCodeField;
        
        private string resultTextField;
        
        private errorCategory resultCategoryField;
        
        private bool resultCategoryFieldSpecified;
        
        private object resultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public systemCodeEnum systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public resultTypeEnum resultType {
            get {
                return this.resultTypeField;
            }
            set {
                this.resultTypeField = value;
                this.RaisePropertyChanged("resultType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string resultText {
            get {
                return this.resultTextField;
            }
            set {
                this.resultTextField = value;
                this.RaisePropertyChanged("resultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public errorCategory resultCategory {
            get {
                return this.resultCategoryField;
            }
            set {
                this.resultCategoryField = value;
                this.RaisePropertyChanged("resultCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCategorySpecified {
            get {
                return this.resultCategoryFieldSpecified;
            }
            set {
                this.resultCategoryFieldSpecified = value;
                this.RaisePropertyChanged("resultCategorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public object resultDetail {
            get {
                return this.resultDetailField;
            }
            set {
                this.resultDetailField = value;
                this.RaisePropertyChanged("resultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/result")]
    public enum resultTypeEnum {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        INFO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/result")]
    public enum errorCategory {
        
        /// <remarks/>
        system,
        
        /// <remarks/>
        logical,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="storeRequest", WrapperNamespace="http://www.server.ru/PrintServerBridgeWS/", IsWrapped=true)]
    public partial class storeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.server.ru/PrintServerBridgeWS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string requestNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.server.ru/PrintServerBridgeWS/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenceService.WebApi.PrintServerBridgeWS.ReportProperties parameters;
        
        public storeRequest() {
        }
        
        public storeRequest(string requestNumber, ReferenceService.WebApi.PrintServerBridgeWS.ReportProperties parameters) {
            this.requestNumber = requestNumber;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="storeResponse", WrapperNamespace="http://www.server.ru/PrintServerBridgeWS/", IsWrapped=true)]
    public partial class storeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.server.ru/PrintServerBridgeWS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenceService.WebApi.PrintServerBridgeWS.serviceResultType serviceResult;
        
        public storeResponse() {
        }
        
        public storeResponse(ReferenceService.WebApi.PrintServerBridgeWS.serviceResultType serviceResult) {
            this.serviceResult = serviceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrintServerBridgeWSChannel : ReferenceService.WebApi.PrintServerBridgeWS.PrintServerBridgeWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintServerBridgeWSClient : System.ServiceModel.ClientBase<ReferenceService.WebApi.PrintServerBridgeWS.PrintServerBridgeWS>, ReferenceService.WebApi.PrintServerBridgeWS.PrintServerBridgeWS {
        
        public PrintServerBridgeWSClient() {
        }
        
        public PrintServerBridgeWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintServerBridgeWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintServerBridgeWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintServerBridgeWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReferenceService.WebApi.PrintServerBridgeWS.storeResponse ReferenceService.WebApi.PrintServerBridgeWS.PrintServerBridgeWS.store(ReferenceService.WebApi.PrintServerBridgeWS.storeRequest request) {
            return base.Channel.store(request);
        }
        
        public ReferenceService.WebApi.PrintServerBridgeWS.serviceResultType store(string requestNumber, ReferenceService.WebApi.PrintServerBridgeWS.ReportProperties parameters) {
            ReferenceService.WebApi.PrintServerBridgeWS.storeRequest inValue = new ReferenceService.WebApi.PrintServerBridgeWS.storeRequest();
            inValue.requestNumber = requestNumber;
            inValue.parameters = parameters;
            ReferenceService.WebApi.PrintServerBridgeWS.storeResponse retVal = ((ReferenceService.WebApi.PrintServerBridgeWS.PrintServerBridgeWS)(this)).store(inValue);
            return retVal.serviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferenceService.WebApi.PrintServerBridgeWS.storeResponse> ReferenceService.WebApi.PrintServerBridgeWS.PrintServerBridgeWS.storeAsync(ReferenceService.WebApi.PrintServerBridgeWS.storeRequest request) {
            return base.Channel.storeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenceService.WebApi.PrintServerBridgeWS.storeResponse> storeAsync(string requestNumber, ReferenceService.WebApi.PrintServerBridgeWS.ReportProperties parameters) {
            ReferenceService.WebApi.PrintServerBridgeWS.storeRequest inValue = new ReferenceService.WebApi.PrintServerBridgeWS.storeRequest();
            inValue.requestNumber = requestNumber;
            inValue.parameters = parameters;
            return ((ReferenceService.WebApi.PrintServerBridgeWS.PrintServerBridgeWS)(this)).storeAsync(inValue);
        }
    }
}
