//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferenceService.WebApi.EventHubWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.server.ru/EventHubWS/", ConfigurationName="EventHubWS.EventHubWS")]
    public interface EventHubWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.server.ru/EventHubWS/sendEventOffline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GID))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(headerType))]
        ReferenceService.WebApi.EventHubWS.sendEventOfflineResponse sendEventOffline(ReferenceService.WebApi.EventHubWS.sendEventOfflineRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.server.ru/EventHubWS/sendEventOffline", ReplyAction="*")]
        System.Threading.Tasks.Task<ReferenceService.WebApi.EventHubWS.sendEventOfflineResponse> sendEventOfflineAsync(ReferenceService.WebApi.EventHubWS.sendEventOfflineRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.server.ru/EventHubWS/")]
    public partial class EventDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string parameterField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("parameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/types")]
    public partial class GID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private systemCodeEnum systemCodeField;
        
        private string branchField;
        
        private TypeObjectEnum typeObjectField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public systemCodeEnum systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TypeObjectEnum typeObject {
            get {
                return this.typeObjectField;
            }
            set {
                this.typeObjectField = value;
                this.RaisePropertyChanged("typeObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/types")]
    public enum systemCodeEnum {
        sys1,
        sys2,
        sys3
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/types")]
    public enum TypeObjectEnum {
        /// <remarks/>
        INTERBANK,
        /// <remarks/>
        DEBITCARD,
        /// <remarks/>
        CREDITCARD
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/types")]
    public partial class headerType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private systemCodeEnum systemCodeField;
        
        private string userIdField;
        
        private string userPasswordField;
        
        private string transactionIdField;
        
        private string parentTransactionIdField;
        
        private string componentIdField;
        
        private string parentComponentIdField;
        
        private string replyToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public systemCodeEnum systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string userPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
                this.RaisePropertyChanged("userPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string parentTransactionId {
            get {
                return this.parentTransactionIdField;
            }
            set {
                this.parentTransactionIdField = value;
                this.RaisePropertyChanged("parentTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string componentId {
            get {
                return this.componentIdField;
            }
            set {
                this.componentIdField = value;
                this.RaisePropertyChanged("componentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string parentComponentId {
            get {
                return this.parentComponentIdField;
            }
            set {
                this.parentComponentIdField = value;
                this.RaisePropertyChanged("parentComponentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string replyTo {
            get {
                return this.replyToField;
            }
            set {
                this.replyToField = value;
                this.RaisePropertyChanged("replyTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/result")]
    public partial class serviceResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private systemCodeEnum systemCodeField;
        
        private resultTypeEnum resultTypeField;
        
        private string resultCodeField;
        
        private string resultTextField;
        
        private errorCategory resultCategoryField;
        
        private bool resultCategoryFieldSpecified;
        
        private object resultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public systemCodeEnum systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public resultTypeEnum resultType {
            get {
                return this.resultTypeField;
            }
            set {
                this.resultTypeField = value;
                this.RaisePropertyChanged("resultType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string resultText {
            get {
                return this.resultTextField;
            }
            set {
                this.resultTextField = value;
                this.RaisePropertyChanged("resultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public errorCategory resultCategory {
            get {
                return this.resultCategoryField;
            }
            set {
                this.resultCategoryField = value;
                this.RaisePropertyChanged("resultCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCategorySpecified {
            get {
                return this.resultCategoryFieldSpecified;
            }
            set {
                this.resultCategoryFieldSpecified = value;
                this.RaisePropertyChanged("resultCategorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public object resultDetail {
            get {
                return this.resultDetailField;
            }
            set {
                this.resultDetailField = value;
                this.RaisePropertyChanged("resultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/result")]
    public enum resultTypeEnum {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        INFO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.ru/service/result")]
    public enum errorCategory {
        
        /// <remarks/>
        system,
        
        /// <remarks/>
        logical,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendEventOfflineRequest", WrapperNamespace="http://www.server.ru/EventHubWS/", IsWrapped=true)]
    public partial class sendEventOfflineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.server.ru/EventHubWS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long eventTypeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.server.ru/EventHubWS/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime eventDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.server.ru/EventHubWS/", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("eventDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ReferenceService.WebApi.EventHubWS.EventDetail[] eventDetails;
        
        public sendEventOfflineRequest() {
        }
        
        public sendEventOfflineRequest(long eventTypeId, System.DateTime eventDate, ReferenceService.WebApi.EventHubWS.EventDetail[] eventDetails) {
            this.eventTypeId = eventTypeId;
            this.eventDate = eventDate;
            this.eventDetails = eventDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendEventOfflineResponse", WrapperNamespace="http://www.server.ru/EventHubWS/", IsWrapped=true)]
    public partial class sendEventOfflineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.server.ru/EventHubWS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenceService.WebApi.EventHubWS.serviceResultType serviceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.server.ru/EventHubWS/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idEvent;
        
        public sendEventOfflineResponse() {
        }
        
        public sendEventOfflineResponse(ReferenceService.WebApi.EventHubWS.serviceResultType serviceResult, long idEvent) {
            this.serviceResult = serviceResult;
            this.idEvent = idEvent;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventHubWSChannel : ReferenceService.WebApi.EventHubWS.EventHubWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventHubWSClient : System.ServiceModel.ClientBase<ReferenceService.WebApi.EventHubWS.EventHubWS>, ReferenceService.WebApi.EventHubWS.EventHubWS {
        
        public EventHubWSClient() {
        }
        
        public EventHubWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventHubWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventHubWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventHubWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReferenceService.WebApi.EventHubWS.sendEventOfflineResponse ReferenceService.WebApi.EventHubWS.EventHubWS.sendEventOffline(ReferenceService.WebApi.EventHubWS.sendEventOfflineRequest request) {
            return base.Channel.sendEventOffline(request);
        }
        
        public ReferenceService.WebApi.EventHubWS.serviceResultType sendEventOffline(long eventTypeId, System.DateTime eventDate, ReferenceService.WebApi.EventHubWS.EventDetail[] eventDetails, out long idEvent) {
            ReferenceService.WebApi.EventHubWS.sendEventOfflineRequest inValue = new ReferenceService.WebApi.EventHubWS.sendEventOfflineRequest();
            inValue.eventTypeId = eventTypeId;
            inValue.eventDate = eventDate;
            inValue.eventDetails = eventDetails;
            ReferenceService.WebApi.EventHubWS.sendEventOfflineResponse retVal = ((ReferenceService.WebApi.EventHubWS.EventHubWS)(this)).sendEventOffline(inValue);
            idEvent = retVal.idEvent;
            return retVal.serviceResult;
        }
        
        public System.Threading.Tasks.Task<ReferenceService.WebApi.EventHubWS.sendEventOfflineResponse> sendEventOfflineAsync(ReferenceService.WebApi.EventHubWS.sendEventOfflineRequest request) {
            return base.Channel.sendEventOfflineAsync(request);
        }
    }
}
