//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferenceService.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReferenceService.WebApi.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустой запрос.
        /// </summary>
        internal static string ErrorRequestRequired {
            get {
                return ResourceManager.GetString("ErrorRequestRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка о полном погашении задолженности.
        /// </summary>
        internal static string ReferenceCode1 {
            get {
                return ResourceManager.GetString("ReferenceCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка об отсутствии действующих кредитных договоров.
        /// </summary>
        internal static string ReferenceCode2 {
            get {
                return ResourceManager.GetString("ReferenceCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка о параметрах кредитного договора.
        /// </summary>
        internal static string ReferenceCode3 {
            get {
                return ResourceManager.GetString("ReferenceCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка о своевременном погашении кредитного договора.
        /// </summary>
        internal static string ReferenceCode4 {
            get {
                return ResourceManager.GetString("ReferenceCode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выписка по счёту.
        /// </summary>
        internal static string ReferenceCode5 {
            get {
                return ResourceManager.GetString("ReferenceCode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует один из обязательных параметров в запросе..
        /// </summary>
        internal static string ReferenceServiceError1 {
            get {
                return ResourceManager.GetString("ReferenceServiceError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка вызова метода формирования pdf справки в PrintServer..
        /// </summary>
        internal static string ReferenceServiceError100 {
            get {
                return ResourceManager.GetString("ReferenceServiceError100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка вызова метода создания события на отправку справки по email в EventHub..
        /// </summary>
        internal static string ReferenceServiceError101 {
            get {
                return ResourceManager.GetString("ReferenceServiceError101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в калькуляторе при формировании справки..
        /// </summary>
        internal static string ReferenceServiceError102 {
            get {
                return ResourceManager.GetString("ReferenceServiceError102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка с указанным номером не найдена..
        /// </summary>
        internal static string ReferenceServiceError150 {
            get {
                return ResourceManager.GetString("ReferenceServiceError150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка находится в не верном статусе..
        /// </summary>
        internal static string ReferenceServiceError151 {
            get {
                return ResourceManager.GetString("ReferenceServiceError151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один из параметров содержит значение не входящее в список для данного поля..
        /// </summary>
        internal static string ReferenceServiceError2 {
            get {
                return ResourceManager.GetString("ReferenceServiceError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один из параметров dateTime содержит не верное значение..
        /// </summary>
        internal static string ReferenceServiceError50 {
            get {
                return ResourceManager.GetString("ReferenceServiceError50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла техническая ошибка, попробуйте повторить попытку позднее..
        /// </summary>
        internal static string ReferenceServiceErrorUserMessage {
            get {
                return ResourceManager.GetString("ReferenceServiceErrorUserMessage", resourceCulture);
            }
        }
    }
}
